### ISSUE TITLE
双击启用V2ray节点程序无响应

### ISSUE THREAD

**Issue by shikkoku** [xinlake/privch-windows#1]
双击传输类型为ws的节点，整个程序无响应，要强制结束。
http和sock端口目前似乎还未能自定义，对于要使用的pac配置里指定了本地ip和端口的配置不友好。

**Comment by privch** [comment]
@shikkoku 最近的 commit 修复了 V2Ray 配置文件的问题，http、socks 端口是程序自动设置的不用手动指定，其他问题待后续更新了
